<img src="https://datasciencedegree.wisconsin.edu/wp-content/themes/data-gulp/images/logo.svg" width="300">

 # <center>DS 710 - Lesson 6a</center>

This notebook will work through some of the basics of the pandas library.

References for the material in this notebook include 
* Chapters 5-8 of your text (the author of the book is also one of the authors of pandas, and it shows!), 
* Official pandas Documentation including the <a href="https://pandas.pydata.org/docs/user_guide/index.html">User Guide</a> and the <a href="https://pandas.pydata.org/docs/reference/index.html#api">API Reference</a>.

---

### Getting started

We'll start by importing NumPy and pandas:

In [1]:
import numpy as np
import pandas as pd

Next, we'll read some data from a csv. Make sure you have downloaded `elements-by-episode.csv` and have it in the same directory as this notebook (Source: <a href="https://github.com/fivethirtyeight/data">FiveThirtyEight</a>). The data given indicates what Bob Ross painted in each episode of "The Joy of Painting", which aired new episodes on PBS from 1983 to 1994. A "1" in an entry indicates that Ross painted the item tagged in that episode, while a "0" indicates that the tagged object was not present in an episode. Note that one column indiactes whether it was his son, Steve Ross, who was painting in that episode instead. The `head` function will show us the first five rows of our DataFrame.

In [2]:
bob_ross = pd.read_csv('elements-by-episode.csv')
bob_ross.head()

,EPISODE,TITLE,APPLE_FRAME,AURORA_BOREALIS,BARN,BEACH,BOAT,BRIDGE,BUILDING,BUSHES,...,TOMB_FRAME,TREE,TREES,TRIPLE_FRAME,WATERFALL,WAVES,WINDMILL,WINDOW_FRAME,WINTER,WOOD_FRAMED
0,S01E01,"""A WALK IN THE WOODS""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
1,S01E02,"""MT. MCKINLEY""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
2,S01E03,"""EBONY SUNSET""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
3,S01E04,"""WINTER MIST""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
4,S01E05,"""QUIET STREAM""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0

We can see that this is a pandas dataframe, find the number of rows and columns in the dataframe, and see the names of all columns as follows:

In [3]:
print(type(bob_ross))
print(bob_ross.shape)
print(bob_ross.columns)

<class 'pandas.DataFrame'>
(403, 69)
Index(['EPISODE', 'TITLE', 'APPLE_FRAME', 'AURORA_BOREALIS', 'BARN', 'BEACH',
       'BOAT', 'BRIDGE', 'BUILDING', 'BUSHES', 'CABIN', 'CACTUS',
       'CIRCLE_FRAME', 'CIRRUS', 'CLIFF', 'CLOUDS', 'CONIFER', 'CUMULUS',
       'DECIDUOUS', 'DIANE_ANDRE', 'DOCK', 'DOUBLE_OVAL_FRAME', 'FARM',
       'FENCE', 'FIRE', 'FLORIDA_FRAME', 'FLOWERS', 'FOG', 'FRAMED', 'GRASS',
       'GUEST', 'HALF_CIRCLE_FRAME', 'HALF_OVAL_FRAME', 'HILLS', 'LAKE',
       'LAKES', 'LIGHTHOUSE', 'MILL', 'MOON', 'MOUNTAIN', 'MOUNTAINS', 'NIGHT',
       'OCEAN', 'OVAL_FRAME', 'PALM_TREES', 'PATH', 'PERSON', 'PORTRAIT',
       'RECTANGLE_3D_FRAME', 'RECTANGULAR_FRAME', 'RIVER', 'ROCKS',
       'SEASHELL_FRAME', 'SNOW', 'SNOWY_MOUNTAIN', 'SPLIT_FRAME', 'STEVE_ROSS',
       'STRUCTURE', 'SUN', 'TOMB_FRAME', 'TREE', 'TREES', 'TRIPLE_FRAME',
       'WATERFALL', 'WAVES', 'WINDMILL', 'WINDOW_FRAME', 'WINTER',
       'WOOD_FRAMED'],
      dtype='str')

We can determine the datatypes of the entries of each column using `dtypes`:

In [4]:
bob_ross.dtypes

EPISODE              str
TITLE                str
APPLE_FRAME        int64
AURORA_BOREALIS    int64
BARN               int64
                   ...
WAVES              int64
WINDMILL           int64
WINDOW_FRAME       int64
WINTER             int64
WOOD_FRAMED        int64
Length: 69, dtype: object

We can pull out the column `TREE` in several ways (Ross painted a lot of trees).

In [5]:
bob_ross.TREE

0      1
1      1
2      1
3      1
4      1
      ..
398    1
399    0
400    1
401    1
402    1
Name: TREE, Length: 403, dtype: int64

In [6]:
bob_ross['TREE']

0      1
1      1
2      1
3      1
4      1
      ..
398    1
399    0
400    1
401    1
402    1
Name: TREE, Length: 403, dtype: int64

---

### Filtering the data

There are quite a few columns in the dataframe (69, in fact); we can choose a few particular columns to display. Suppose we want to know about the presence of trees and mountains.

In [7]:
bob_ross_tm = bob_ross[['EPISODE', 'TITLE', 'CONIFER', 'DECIDUOUS', 'PALM_TREES', 'MOUNTAIN', 'MOUNTAINS', 'SNOWY_MOUNTAIN', 'TREE', 'TREES']]
bob_ross_tm.head(10)

,EPISODE,TITLE,CONIFER,DECIDUOUS,PALM_TREES,MOUNTAIN,MOUNTAINS,SNOWY_MOUNTAIN,TREE,TREES
0,S01E01,"""A WALK IN THE WOODS""",0,1,0,0,0,0,1,1
1,S01E02,"""MT. MCKINLEY""",1,0,0,1,0,1,1,1
2,S01E03,"""EBONY SUNSET""",1,0,0,1,1,0,1,1
3,S01E04,"""WINTER MIST""",1,0,0,1,0,1,1,1
4,S01E05,"""QUIET STREAM""",0,1,0,0,0,0,1,1
5,S01E06,"""WINTER MOON""",1,0,0,1,1,1,1,1
6,S01E07,"""AUTUMN MOUNTAINS""",0,1,0,1,1,1,1,1
7,S01E08,"""PEACEFUL VALLEY""",1,0,0,1,1,0,1,1
8,S01E09,"""SEASCAPE""",0,0,0,0,0,0,0,0
9,S01E10,"""MOUNTAIN LAKE""",1,1,0,1,0,0,1,1

Maybe we only care about Season 15 of "The Joy of Painting". Then, we can select just the rows that correspond to Season 15, as follows.

In [8]:
bob_ross_tm_S15 = bob_ross_tm[bob_ross_tm.EPISODE.str.contains('S15')]
bob_ross_tm_S15

,EPISODE,TITLE,CONIFER,DECIDUOUS,PALM_TREES,MOUNTAIN,MOUNTAINS,SNOWY_MOUNTAIN,TREE,TREES
182,S15E01,"""SPLENDOR OF WINTER""",1,1,0,0,0,0,1,1
183,S15E02,"""COLORS OF NATURE""",0,1,0,0,0,0,1,1
184,S15E03,"""GRANDPA'S BARN""",0,1,0,0,0,0,1,1
185,S15E04,"""PEACEFUL REFLECTIONS""",0,0,0,0,0,0,0,0
186,S15E05,"""HIDDEN WINTER MOON OVAL""",1,0,0,1,1,1,1,1
187,S15E06,"""WAVES OF WONDER""",0,0,0,0,0,0,0,0
188,S15E07,"""CABIN BY THE POND""",1,1,0,0,0,0,1,1
189,S15E08,"""FALL STREAM""",0,1,0,1,1,0,1,1
190,S15E09,"""CHRISTMAS EVE SNOW""",1,0,0,1,1,1,1,1
191,S15E10,"""FOREST DAWN OVAL""",0,1,0,0,0,0,1,1
192,S15E11,"""PATHWAY TO AUTUMN""",0,1,0,0,0,0,1,1
193,S15E12,"""DEEP FOREST LAKE""",0,1,0,0,0,0,1,1
194,S15E13,"""PEAKS OF MAJESTY""",1,0,0,1,1,0,1,1

🧠 In the cell below, try writing code to display all episodes from the original file whose titles contain the word "SNOW".

In [10]:
bob_ross_snow = bob_ross[bob_ross.TITLE.str.contains('SNOW')]
bob_ross_snow

,EPISODE,TITLE,APPLE_FRAME,AURORA_BOREALIS,BARN,BEACH,BOAT,BRIDGE,BUILDING,BUSHES,...,TOMB_FRAME,TREE,TREES,TRIPLE_FRAME,WATERFALL,WAVES,WINDMILL,WINDOW_FRAME,WINTER,WOOD_FRAMED
11,S01E12,"""SNOWFALL""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
70,S06E06,"""SNOW TRAIL""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
172,S14E04,"""SNOWY SOLITUDE""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
190,S15E09,"""CHRISTMAS EVE SNOW""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
203,S16E09,"""BARN IN SNOW OVAL""",0,0,1,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
234,S19E01,"""SNOWFALL MAGIC""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
237,S19E04,"""SNOWY MORN""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
311,S24E13,"""SNOWBOUND CABIN""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
327,S26E03,"""FIRST SNOW""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
331,S26E07,"""SNOW BIRCH""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
348,S27E11,"""SPLENDOR OF A SNOWY WHITE""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
391,S31E02,"""BEFORE THE SNOWFALL""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0

The `mean` function will calculate the means of columns; starting with `pandas` 2.0, you need to specify `numeric_only=True` if you want to ignore columns with non-numeric values.

🧠 Which category of tree/mountain was most popular in Season 15? Did Ross ever paint a single tree in a painting during Season 15?

In [11]:
bob_ross_tm_S15.mean(numeric_only = True)

CONIFER           0.384615
DECIDUOUS         0.615385
PALM_TREES        0.000000
MOUNTAIN          0.307692
MOUNTAINS         0.307692
SNOWY_MOUNTAIN    0.153846
TREE              0.846154
TREES             0.846154
dtype: float64

---

### Adding a new column, & views/copies

Let's add a column that is the sum of all the tree type columns: that is, a column that will tell us how many of the three specific tree types appear in each painting.

#### A first attempt to add a new trees column

First, we want to offer you a training experience on writing correct pandas code.  So, we'll start with some code that doesn't work (in that it generates a warning).

⚠️ We would really like to be able to write the following code:

In [13]:
# this code will generate a warning
bob_ross_tm = bob_ross[['EPISODE', 'TITLE', 'CONIFER', 'DECIDUOUS', 'PALM_TREES', 'MOUNTAIN', 'MOUNTAINS', 'SNOWY_MOUNTAIN', 'TREE', 'TREES']]
bob_ross_tm['TREE_TYPE_TOTALS'] = bob_ross_tm.CONIFER + bob_ross_tm.DECIDUOUS + bob_ross_tm.PALM_TREES

In [14]:
# this code will generate the same warning, the first time it is run
bob_ross = pd.read_csv('elements-by-episode.csv')
bob_ross_tm = bob_ross[['EPISODE', 'TITLE', 'CONIFER', 'DECIDUOUS', 'PALM_TREES', 'MOUNTAIN', 'MOUNTAINS', 'SNOWY_MOUNTAIN', 'TREE', 'TREES']]
bob_ross_tm.loc['TREE_TYPE_TOTALS'] = bob_ross_tm.CONIFER +  bob_ross_tm.DECIDUOUS +  bob_ross_tm.PALM_TREES

##### Why does this happen?

Do your best to [grok](https://en.wikipedia.org/wiki/Grok) this.  It may take some time for this to make sense, and that's ok!

Short answer: views.

* An SO post, [How to deal with SettingWithCopyWarning in Pandas](https://stackoverflow.com/questions/20625582/how-to-deal-with-settingwithcopywarning-in-pandas), discusses the warning, and how to handle it.  In particular, see the answer by user cs95, section "The "XY Problem": What am I doing wrong?".  
* Here's some official documentation about the topic. [Pandas documentation: Indexing and selecting data](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html).  
* And this post, [Real Python: SettingWithCopyWarning in Pandas: Views vs Copies](https://realpython.com/pandas-settingwithcopywarning/) has a great exposition of the problem, complete with pictures!  (Use an ad-blocker, or the page is unviewable 😕)

Summary of why the error happens:
* Many operations in pandas produce "views" instead of copies.  This is for performance, so that tons of data isn't needlessly copied in memory.  Views are containers that "point to" existing data, instead of duplicating it.
* Other operations in pandas produce "copies" -- so that the data is duplicated.
* Setting data in views can produce weird behaviour, because the setting operation can modify a container you didn't expect to modify.

The specific cause in this case:
* When we made `bob_ross_tm`, we produced a view into the old data frame.  So, setting data into this data frame may produce the warning.

A specific solution in this case:
* When making `bob_ross_tm`, make it a *copy* of the data.  
* That is, use `bob_ross_tm = bob_ross[['EPISODE']].copy()

There are other solutions, too. See below for some options.  

##### How to tell if you have copy /view

It's not immediately obvious how to tell whether you have a copy or a view into another data frame / object in pandas.  This SO post, [Checking whether data frame is copy or view in Pandas](https://stackoverflow.com/questions/26879073/checking-whether-data-frame-is-copy-or-view-in-pandas), gives some instruction.  

##### Conclusion
Listen to this warning.  Practice will lead you to program using pandas in ways that don't produce this warning.  And, don't give in to the temptation to disable the warning.  That way lies the dark side (and nasty bugs 🦂).

#### More-correct ways of adding the new column

These are several ways of adding the new `TREE_TYPE_TOTALS` column.  All of them essentially copy the data, solving the view/copy problem.  See the next three cells.  (Note, we have the import and read_csv calls so that it makes it easy to play with these cells, if you restart the kernel to get a fresh start).

In [16]:
# solution 1 -- use .assign
# https://pandas.pydata.org/pandas-docs/version/0.23.1/generated/pandas.DataFrame.assign.html
# produces a deep copy, getting around the view problem
import pandas as pd
bob_ross = pd.read_csv('elements-by-episode.csv')
bob_ross_tm = bob_ross[['EPISODE', 'TITLE', 'CONIFER', 
                        'DECIDUOUS', 'PALM_TREES', 'MOUNTAIN', 
                        'MOUNTAINS', 'SNOWY_MOUNTAIN', 'TREE', 'TREES']]
bob_ross_tm = bob_ross_tm.assign(TREE_TYPE_TOTALS =  bob_ross_tm.CONIFER +  bob_ross_tm.DECIDUOUS +  bob_ross_tm.PALM_TREES)
bob_ross_tm

,EPISODE,TITLE,CONIFER,DECIDUOUS,PALM_TREES,MOUNTAIN,MOUNTAINS,SNOWY_MOUNTAIN,TREE,TREES,TREE_TYPE_TOTALS
0,S01E01,"""A WALK IN THE WOODS""",0,1,0,0,0,0,1,1,1
1,S01E02,"""MT. MCKINLEY""",1,0,0,1,0,1,1,1,1
2,S01E03,"""EBONY SUNSET""",1,0,0,1,1,0,1,1,1
3,S01E04,"""WINTER MIST""",1,0,0,1,0,1,1,1,1
4,S01E05,"""QUIET STREAM""",0,1,0,0,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
398,S31E09,"""EVERGREEN VALLEY""",1,0,0,1,1,1,1,1,1
399,S31E10,"""BALMY BEACH""",0,0,1,0,0,0,0,0,1
400,S31E11,"""LAKE AT THE RIDGE""",1,1,0,1,1,1,1,1,2
401,S31E12,"""IN THE MIDST OF WINTER""",1,1,0,0,0,0,1,1,2
402,S31E13,"""WILDERNESS DAY""",0,1,0,1,0,0,1,1,1

In [17]:
# solution 2a -- add `.copy()` when making `bob_ross_tm`
# then use `loc` or whatever other method you want
import pandas as pd
bob_ross = pd.read_csv('elements-by-episode.csv')
bob_ross_tm = bob_ross[['EPISODE', 'TITLE', 'CONIFER', 
                        'DECIDUOUS', 'PALM_TREES', 'MOUNTAIN', 
                        'MOUNTAINS', 'SNOWY_MOUNTAIN', 'TREE', 'TREES']].copy()
bob_ross_tm.loc[:,'TREE_TYPE_TOTALS'] = bob_ross_tm.CONIFER +  bob_ross_tm.DECIDUOUS +  bob_ross_tm.PALM_TREES

In [18]:
# solution 2b -- add `.copy()` when making `bob_ross_tm`
# then we can use the line we really wanted to the first time
import pandas as pd
bob_ross = pd.read_csv('elements-by-episode.csv')
bob_ross_tm = bob_ross[['EPISODE', 'TITLE', 'CONIFER', 
                        'DECIDUOUS', 'PALM_TREES', 'MOUNTAIN', 
                        'MOUNTAINS', 'SNOWY_MOUNTAIN', 'TREE', 'TREES']].copy()
bob_ross_tm['TREE_TYPE_TOTALS'] = bob_ross_tm.CONIFER + bob_ross_tm.DECIDUOUS + bob_ross_tm.PALM_TREES

---

### Sorting 

We can order the episodes according to how many distinct tree types appear, and then by episode number.

In [19]:
bob_ross_tm = bob_ross_tm.sort_values(by=['TREE_TYPE_TOTALS','EPISODE'])
bob_ross_tm

,EPISODE,TITLE,CONIFER,DECIDUOUS,PALM_TREES,MOUNTAIN,MOUNTAINS,SNOWY_MOUNTAIN,TREE,TREES,TREE_TYPE_TOTALS
8,S01E09,"""SEASCAPE""",0,0,0,0,0,0,0,0,0
33,S03E08,"""NIGHT LIGHT""",0,0,0,0,0,0,0,0,0
57,S05E06,"""OCEAN SUNRISE""",0,0,0,0,0,0,0,0,0
60,S05E09,"""ANATOMY OF A WAVE""",0,0,0,0,0,0,0,0,0
63,S05E12,"""INDIAN GIRL""",0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
383,S30E07,"""THROUGH THE WINDOW""",1,1,0,0,0,0,1,1,2
385,S30E09,"""MOUNTAINS OF GRACE""",1,1,0,1,1,1,1,1,2
388,S30E12,"""EVENING'S GLOW""",1,1,0,0,0,0,1,1,2
400,S31E11,"""LAKE AT THE RIDGE""",1,1,0,1,1,1,1,1,2
401,S31E12,"""IN THE MIDST OF WINTER""",1,1,0,0,0,0,1,1,2

Suppose we wish to determine the number of episodes in which each of the tree and mountain categories appears. We can sum down across rows (down columns) as follows:

In [20]:
bob_ross_tm.sum(axis=0)

EPISODE             S01E09S03E08S05E06S05E09S05E12S06E10S07E05S07E...
TITLE               "SEASCAPE""NIGHT LIGHT""OCEAN SUNRISE""ANATOMY...
CONIFER                                                           212
DECIDUOUS                                                         227
PALM_TREES                                                          9
MOUNTAIN                                                          160
MOUNTAINS                                                          99
SNOWY_MOUNTAIN                                                    109
TREE                                                              361
TREES                                                             337
TREE_TYPE_TOTALS                                                  448
dtype: object

Finally, let's write our manipulated data back to a new csv:

In [21]:
bob_ross_tm.to_csv('bob-ross_trees_mountains.csv', index=False)

🧠 Play with other sorts

In [ ]:
# your code here

---

## When you're done

🧠 After completing the guided practice above, log onto Canvas to complete Quiz 6a. You may wish to keep this notebook open while you work.

In [28]:
bob_ross_2 = bob_ross[bob_ross.EPISODE.str.contains('09')]
bob_ross_2.head()

,EPISODE,TITLE,APPLE_FRAME,AURORA_BOREALIS,BARN,BEACH,BOAT,BRIDGE,BUILDING,BUSHES,...,TOMB_FRAME,TREE,TREES,TRIPLE_FRAME,WATERFALL,WAVES,WINDMILL,WINDOW_FRAME,WINTER,WOOD_FRAMED
8,S01E09,"""SEASCAPE""",0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,S02E09,"""BLACK & WHITE SEASCAPE""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,1,0,0,0,0
34,S03E09,"""THE OLD MILL""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
47,S04E09,"""COOL WATERS""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
60,S05E09,"""ANATOMY OF A WAVE""",0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [37]:
bob_ross.shape

(403, 69)

In [39]:
bob_ross_2

,EPISODE,TITLE,APPLE_FRAME,AURORA_BOREALIS,BARN,BEACH,BOAT,BRIDGE,BUILDING,BUSHES,...,TOMB_FRAME,TREE,TREES,TRIPLE_FRAME,WATERFALL,WAVES,WINDMILL,WINDOW_FRAME,WINTER,WOOD_FRAMED
8,S01E09,"""SEASCAPE""",0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,S02E09,"""BLACK & WHITE SEASCAPE""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,1,0,0,0,0
34,S03E09,"""THE OLD MILL""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
47,S04E09,"""COOL WATERS""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
60,S05E09,"""ANATOMY OF A WAVE""",0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
73,S06E09,"""HIGH CHATEAU""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
86,S07E09,"""LAKE BY MOUNTAIN""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
99,S08E09,"""MAJESTIC PINE""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
104,S09E01,"""WINTER EVERGREENS""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
105,S09E02,"""SURF'S UP""",0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
106,S09E03,"""RED SUNSET""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
107,S09E04,"""MEADOW ROAD""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
108,S09E05,"""WINTER OVAL""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
109,S09E06,"""SECLUDED BEACH""",0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
110,S09E07,"""FOREST HILLS""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
111,S09E08,"""LITTLE HOUSE BY-THE-ROAD""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
112,S09E09,"""MOUNTAIN PATH""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
113,S09E10,"""COUNTRY CHARM""",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
114,S09E11,"""NATURE'S PARADISE""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
115,S09E12,"""MOUNTAIN-BY-THE-SEA""",0,0,0,1,0,0,0,1,...,0,1,0,0,0,1,0,0,0,0
116,S09E13,"""MOUNTAIN HIDE-AWAY""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
125,S10E09,"""MOUNTAIN OVAL""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
138,S11E09,"""WINTER BARN""",0,0,1,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
151,S12E09,"""TROPICAL SEASCAPE""",0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
164,S13E09,"""EMERALD WATERS""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
177,S14E09,"""RIVERSIDE ESCAPE OVAL""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
190,S15E09,"""CHRISTMAS EVE SNOW""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
203,S16E09,"""BARN IN SNOW OVAL""",0,0,1,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
216,S17E09,"""LAKE VIEW""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
229,S18E09,"""SEASCAPE FANTASY""",0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
242,S19E09,"""EBB TIDE""",0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
255,S20E09,"""WINTER'S PARADISE""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
268,S21E09,"""INDIAN SUMMER""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
281,S22E09,"""HAVEN IN THE VALLEY""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
294,S23E09,"""TOWARD DAY'S END""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
307,S24E09,"""ICY LAKE""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
320,S25E09,"""DOWNSTREAM VIEW""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
333,S26E09,"""TRANQUIL WOODED STREAM""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
346,S27E09,"""ISLAND PARADISE""",0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
359,S28E09,"""WINTER'S GRACE""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
372,S29E09,"""STORM ON THE HORIZON""",0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
385,S30E09,"""MOUNTAINS OF GRACE""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
398,S31E09,"""EVERGREEN VALLEY""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0

In [44]:
bob_ross.ndim

2